# Generated by Django 5.2.3 on 2025-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('university_id', models.CharField(blank=True, max_length=10)),
                ('applied_for', models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Staff', 'Staff'), ('ItStaff', 'ItStaff')], max_length=20, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Staff', 'Staff'), ('ItStaff', 'ItStaff')], max_length=20, null=True)),
                ('is_varified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
        ),
    ]
