# Generated by Django 5.2.3 on 2025-06-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
