# Generated by Django 5.2.3 on 2025-06-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='issues',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='issues_type',
            field=models.CharField(choices=[('software', 'Software Issues'), ('hardware', 'Hardware Issues')], default='None', max_length=10),
        ),
    ]
